version: "3.8"
services:
  netgear-rebooter:
    image: netgear-rebooter
    build:
      context: /custom/netgear-rebooter/
      dockerfile: /custom/netgear-rebooter/Dockerfile
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Chicago
    env_file:
      - /custom/netgear-rebooter/.env
    ports:
      - 3000:3000
    volumes:
      - /mnt/system/docker/netgear-rebooter:/config # Log file writes to here
